# Generated by Django 5.2.17 on 2026-09-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_organization_experience_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_display',
            field=models.CharField(blank=True, help_text='Contoh: May 2026 - Present', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Paste link foto di sini', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('committee', 'Committee'), ('teaching-assistant', 'Teaching Assistant'), ('volunteer', 'Volunteer')], default='organization', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
