# Generated by Django 5.2.17 on 2026-09-19 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
