# Generated by Django 5.2.17 on 2026-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_options_experience_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
